spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/jobportal?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# JWT Config
jobportal.app.jwtSecret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jobportal.app.jwtExpirationMs=86400000

# File Upload Size
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# AI Configuration
gemini.api.key=AIzaSyCU-gLUVKBjAnLV4KQqteG_k_NYI45WHRo